language: rust

os:
  - linux
  - windows

rust:
  - stable
  - beta
  - nightly

before_install:
  - if [[ "$TRAVIS_OS_NAME" = 'windows' ]]; then choco install protoc; fi

addons:
  apt:
    sources:
      - sourceline: "ppa:maarten-fonville/protobuf"

    packages:
      - protobuf-compiler
      - libprotoc-dev

git:
  depth: 1

cache: cargo

matrix:
  allow_failures:
    - os: windows

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
