language: rust

os:
  - linux

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    sources:
    - sourceline: "ppa:maarten-fonville/protobuf"

    packages:
    - protobuf-compiler
    - libprotoc-dev

git:
  depth: 1

cache: cargo

matrix:
  allow_failures:
    - rust: stable

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
