[package]
name = "qni-core-rs"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[build-dependencies]
protoc-rust = "2.0"

[dependencies]
log = "*"
protobuf = "*"
multiqueue = "*"
bus = "*"
