[package]
name = "qni-core-rs"
version = "0.1.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
cargo-features = ["edition"]

[build-dependencies]
protoc-rust = "*"
rustc_version = "*"

[dependencies]
libc = "*"
log = "*"
protobuf = "*"
multiqueue = "*"
