[package]
name = "qni-core-rs"
version = "0.2.0"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"

[build-dependencies]
protoc-rust = "*"

[dependencies]
log = "*"
protobuf = "*"
multiqueue = "*"
chrono = "*"
