[package]
name = "qni-core-rs"
description = "qni core library"
version = "0.2.5"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
repository = "https://github.com/Riey/qni-core-rs"
homepage = "https://github.com/Riey/qni-core-rs"
license = "LGPL-3.0"
readme = "README.md"

exclude = [
    "src/protos/qni_api.rs",
    ".gitignore",
    ".gitmodules",
    ".travis.yml",
    ".vscode/**/*",
    ".idea/**/*",
]

[build-dependencies]
protoc-rust = "2.2.0"

[dependencies]
protobuf = "2.2.0"
chrono = "0.4.6"
bus = "2.0.1"
atomic-option = "0.1.2"
