[package]
name = "qni-core-rs"
description = "qni core library"
version = "0.2.3"
authors = ["Riey <creeper844@gmail.com>"]
edition = "2018"
repository = "https://github.com/Riey/qni-core-rs"
homepage = "https://github.com/Riey/qni-core-rs"
license-file = "LICENSE"
readme = "README.md"

exclude = [
    "src/protos/qni_api.rs",
    ".gitignore",
    ".gitmodules",
    ".travis.yml",
    ".vscode/**/*",
    ".idea/**/*",
]

[build-dependencies]
protoc-rust = "2.2.0"

[dependencies]
log = "0.4.6"
protobuf = "2.2.0"
multiqueue = "0.3.2"
chrono = "0.4.6"
